name: Move new issues onto Issue triage board

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    # Skip in forks
    if: github.repository == 'vector-im/element-android'
    steps:
      - uses: alex-page/github-project-automation-plus@303f24a24c67ce7adf565a07e96720faf126fe36
        with:
          project: Issue triage
          column: Incoming
          repo-token: ${{ secrets.ELEMENT_BOT_TOKEN }}
